tunnel: 87be5433-d54b-4036-be87-a557783e0f59
credentials-file: C:\Users\Usuario\.cloudflared\87be5433-d54b-4036-be87-a557783e0f59.json

ingress:
  - hostname: inspetorbudganja.com.br
    service: http://localhost:8080
  - hostname: www.inspetorbudganja.com.br
    service: http://localhost:8080
  - service: http_status:404
